# Generated by Django 4.1.1 on 2022-09-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inf',
            name='about',
        ),
        migrations.RemoveField(
            model_name='inf',
            name='name',
        ),
        migrations.AddField(
            model_name='inf',
            name='name1',
            field=models.CharField(default=1, max_length=30, verbose_name='Inf name1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inf',
            name='name2',
            field=models.TextField(default=1, max_length=30, verbose_name='Inf name2'),
            preserve_default=False,
        ),
    ]
