# Generated by Django 4.1.1 on 2022-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_inf_about_remove_inf_name_inf_name1_inf_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30, verbose_name='HomeSlider1 name1')),
                ('name2', models.CharField(max_length=30, verbose_name='HomeSlider1 name2')),
                ('about', models.TextField(verbose_name='HomeSlider1 about')),
            ],
            options={
                'verbose_name': 'HomeSlider1',
                'verbose_name_plural': 'HomeSlider1s',
            },
        ),
        migrations.CreateModel(
            name='HomeSlider1Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30, verbose_name='HomeSlider1 name1')),
                ('name2', models.CharField(max_length=30, verbose_name='HomeSlider1 name2')),
                ('about', models.TextField(verbose_name='HomeSlider1 about')),
            ],
            options={
                'verbose_name': 'HomeSlider1Active',
                'verbose_name_plural': 'HomeSlider1sActive',
            },
        ),
    ]
